### ISSUE TITLE
Dependices conflict error

### ISSUE THREAD

**Issue by HaoDingg** [LirongWu/Prompt-DDG#1]
I use the exact same environment.yaml file to create the environment and found missing module nni.
Tried to install newest version nni but it conflicts with numpy version 1.20.1 and automatically installed a 2.0.0 numpy.
Could you add the correct nni version to the environment?

Thanks for your great work by the way.

**Comment by HaoDingg** [comment]
okay i just solved this by install numpy==1.26.4. 
Module easydict is also missed by the way.
After installing latest nni and easydict, then change numpy version to 1.26.4, I can run this project successfully.

**Comment by HaoDingg** [comment]
okay i just solved this by install numpy==1.26.4. 
Module easydict is also missed by the way.
After installing latest nni and easydict, then change numpy version to 1.26.4, I can run this project successfully.

**Comment by HaoDingg** [comment]
And pip install mkl==2024.0 to solve a strange import torch error which is said in the issue  [https://github.com/pytorch/pytorch/issues/123097](url)

**Comment by LirongWu** [comment]
Thank you very much for the heads up, we have added the easydict. Additionally the nni package is not a required item, and I've removed the call to this package from the code for now.
