### ISSUE TITLE
How to make mutation DDG predictions for any other protein complexes with Prompt-DDG?

### ISSUE THREAD

**Issue by Jiasheng321** [LirongWu/Prompt-DDG#4]
Congratulations on your great work and paper!

I installed Prompt-DDG as described and run/ran the command line as python -B train.py --ckpt_path ../trained_models/ddg_model.ckpt.  The above command seemed to produce some reasonable outputs including results.csv in the results directory of Prompt-DDG, however, which seemed to be about Skempi data mutations’ predictions.

My question is, how could I use the data/7FAE_RBD_Fv_mutation.yml, and data/7FAE_RBD_Fv.pdb files, in the data directory of Prompt-DDG, to predict the DDG changes of the mutations in the 7FAE_RBD_Fv_mutation.yml file, or any other protein complexes? Do I need to modify the train.py python script? And what is is the command line to run the modified python script?  Could you please give me some more detailed instructions on how to do it, because I am new to Python.  Thanks very much.

Sincerely,
Jiasheng

**Comment by LirongWu** [comment]
To predict the DDG of SARS (7FAE_RBD_Fv) using Prompt-DDG, you need to do: (1) uncomment Line 219 of train.py in dataset.py; (2) run train.py. If you want to use Prompt-DDG for prediction of any of the protein complexes, you need to write a dataloader yourself as the example (get_SARS_data() function in dataset.py), which requires quite a bit of work.
